### ISSUE TITLE
Evaluate glob 6.x

### ISSUE THREAD

**Issue by phated** [gulpjs/glob-stream#57]
Need to look through the breaking changes, see if they affect our usage and if we need to bump major.

**Comment by erikkemperman** [comment]
Turns out I've basically been evaluating glob 7.0.6, having `npm link`ed it in my glob-stream, and transitively in my vinyl-fs and vinyl-prepare projects.

For what it's worth, all tests pass in glob-stream (master) and vinyl-fs (master) and with the vinyl-fs / vinyl-prepare split as well).

Haven't seen explicit release notes, but from the README I guess the most significant change is negated patterns with `!`, support for which was deprecated in glob 5 and removed in 6, favouring the `ignore` option to do the same.

If that is the extent of potential annoyance of upgrading glob, is it already too much?

**Comment by phated** [comment]
I'm working on a branch that switches to the ignore option and upgrades to 7.x - This will land in the next major.  Thanks for following up though.

**Comment by erikkemperman** [comment]
Excellent!

I've hatched an evil scheme that might allow glob-stream to be leveraged even when implementing e.g. a virtual or remote filesystem adapter.

I think that'd be nice because otherwise custom adapters would have to do their own globbing, or just not support glob patterns, period.

A PR is pending on node-glob, [here](https://github.com/isaacs/node-glob/pull/285). I think it's pretty solid... But I haven't heard back and it might not amount to anything.

If it were accepted, though, it'd help if the glob-stream dependency were easily made up to date!

**Comment by phated** [comment]
Interesting.  I still don't think vinyl-prepare should deal with globbing, reading, etc but let's see where the node-glob PR goes.

**Comment by erikkemperman** [comment]
It wouldn't matter much if the call to glob-stream in vinyl-prepare or vinyl-fs, it seems to me -- the point is that peers of vinyl-fs could use glob-stream (if they wanted to) and easily support asterisk patterns and so on in a way that is automatically analogous to vinyl-fs.
